### DISCUSSION TITLE
Github greeting action

### DISCUSSION THREAD

**Discussion by Dun-sin** [rupali-codes/LinksHub#416] [General]
Not sure why it's still not working @rupali-codes 
i'm thinking maybe to remove the name under the steps
```
name: Greetings
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
     // remove name here
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          issue-message: |
            ${{ if github.event_name == 'pull_request' }}
              Great job, ${{ github.actor }}! 🎉 Thank you for submitting your pull request in LinksHub. Your contribution is valuable and we appreciate your efforts to improve our project. We'll review your changes and provide feedback as soon as possible. Keep up the great work!
            ${{ else if github.event_name == 'issues' }}
              Hello, ${{ github.actor }}! 🎉 Thank you for creating a new issue in LinksHub. Your contribution is highly appreciated, and we are eager to collaborate with you to resolve the issue. Your hard work and dedication are commendable. Keep up the excellent work!
            ${{ endif }}

```
