### ISSUE TITLE
[Feature] Broken Link Checker - Github Action

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2357]
### Description

I believe that it will be a great idea to setup a GitHub action that runs periodically and checks for broken links.

I just implemented it in my project and I would like to share my knowledge and received feedback to make it better.

### Screenshots

here is an example from my own project:
![image](https://github.com/rupali-codes/LinksHub/assets/25883220/9a469ddc-ab35-4062-a475-67ca6a3f6bce)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
That seems possible @JuanPabloDiaz. @rupali-codes, @Anmol-Baranwal, @aftabrehan, thoughts?

**Comment by rupali-codes** [comment]
> That seems possible @JuanPabloDiaz. @rupali-codes, @Anmol-Baranwal, @aftabrehan, thoughts?

it seems great though, but how does that actually work @JuanPabloDiaz ?

**Comment by JuanPabloDiaz** [comment]
> > That seems possible @JuanPabloDiaz. @rupali-codes, @Anmol-Baranwal, @aftabrehan, thoughts?
> 
> it seems great though, but how does that actually work @JuanPabloDiaz ?

It will be a Github action to check for broken links in Markdown, HTML, and text files using [Lychee](https://lychee.cli.rs/), a fast link checker written in Rust.

Here is a full example of a GitHub workflow file:

It will check all repository links once per day and create an issue in case of errors.

```yaml
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```
