### ISSUE TITLE
[Feature] Create GitHub workflow to assign issues to users on comment 'take'

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2507]
### Description
Users should be able to comment "take" on an issue to be auto-assigned the issue.

This creates a good experience for OSS users. They can grab an issue and it will make sure nobody else is working on it.

```yml
// .github/workflows/auto-assign-issues.yml

# This workflow has been inspired by https://github.com/MrPowers/quinn/blob/main/.github/workflows/assign-on-comment.yml

name: Auto Assign Issues On Comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: (!github.event.issue.pull_request) && github.event.comment.body == 'take'
    concurrency:
      # Only run one a time per user
      group: ${{ github.actor }}-auto-assign-issue
    steps:
      - name: Check if issue can be assigned
        id: check-assignee
        run: |
          # Check if the user is already assigned to the issue
          RESPONSE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -LI https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees/${{ github.event.comment.user.login }} -o /dev/null -w '%{http_code}' -s)
          echo "HTTP_CODE=$RESPONSE" >> $GITHUB_ENV

      - name: Assign issue to commenter
        if: env.HTTP_CODE == '204'
        run: |
          # Assign the issue to the user who commented 'take'
          echo "Assigning issue #${{ github.event.issue.number }} to @${{ github.event.comment.user.login }}"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"assignees": ["${{ github.event.comment.user.login }}"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log failure to assign
        if: env.HTTP_CODE != '204'
        run: |
          # Log the failure to assign the issue
          echo "Issue #${{ github.event.issue.number }} cannot be assigned to @${{ github.event.comment.user.login }}. HTTP response code: ${{ env.HTTP_CODE }}"
```

### Screenshots

Visual example:

![image](https://github.com/user-attachments/assets/5a77cc60-eb47-44cf-8b26-f261d4cf4d42)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
