### ISSUE TITLE
[OTHER] Update dependabot workflow

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#979]
### What would you like to share or ask?

- To ensure adherence to standard conventions, we can include proper commit prefixes.
- Additionally, we can apply the label `📦 dependencies` to the PR

> If you would like further customizations, such as wildcard ignoring of dependencies, please let me know.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal i didn't get it, could you please elaborate a bit more?

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 

The current workflow:
```yml
version: 2
updates:
  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

The PR from the bot lacks a few things. Firstly, it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.
